/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package GUI;
package com.mycompany.lab3;

import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;


public class MakeNewReservation extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(MakeNewReservation.class.getName());

    private Client client;   
  
    private String username;

    public MakeNewReservation(String username) {
        initComponents();
        client = new Client();
        this.username=username;
        fillComboBoxes();
        applyDesign();
   
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            timeSelectedActionPerformed(evt);
        }
    });
    
    }
    
 // fill in the lists
    private void fillComboBoxes() {
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"R1", "R2", "R3"})); // المطاعم
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"})); // الأيام
    }
    /*
private void fillComboBoxes() {
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"R1", "R2", "R3"})); // restaurants
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"})); // days
}*/
    
     // =============== ✨ DESIGN (safe) ✨ ===============
    private void applyDesign() {

        // خلفية بيج
        getContentPane().setBackground(new java.awt.Color(245, 240, 230));

        java.awt.Color brown = new java.awt.Color(70, 40, 20);
        java.awt.Font labelFont = new java.awt.Font("Serif", java.awt.Font.ITALIC, 18);

        // تنسيق اللابلز
        jLabel1.setForeground(brown);
        jLabel2.setForeground(brown);
        jLabel3.setForeground(brown);
        jLabel4.setForeground(brown);

        jLabel1.setFont(labelFont);
        jLabel2.setFont(labelFont);
        jLabel3.setFont(labelFont);
        jLabel4.setFont(labelFont);

        // تنسيق الكومبو بوكس
        java.awt.Font comboFont = new java.awt.Font("Serif", java.awt.Font.PLAIN, 16);

        jComboBox1.setFont(comboFont);
        jComboBox2.setFont(comboFont);
        jComboBox3.setFont(comboFont);
        jComboBox4.setFont(comboFont);

        // تنسيق الأزرار
        styleButton(jButton3, brown);
        styleButton(jButton4, brown);
    }

    private void styleButton(javax.swing.JButton btn, java.awt.Color brown) {

        btn.setFont(new java.awt.Font("Serif", java.awt.Font.ITALIC, 18));
        btn.setForeground(brown);
        btn.setBackground(new java.awt.Color(255, 250, 245));
        btn.setBorder(javax.swing.BorderFactory.createLineBorder(brown, 2));
        btn.setFocusPainted(false);

        // Hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(240, 225, 210));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(255, 250, 245));
            }
        });
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Make new reservation");

        jLabel1.setText("please choose the date to show the available time slots");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("please choose the Restrunt");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton3.setText("Show available times");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Please choose the prefered time slot");

        jButton4.setText("Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel3.setText("Table number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
// show available times button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String restaurant = jComboBox1.getSelectedItem().toString();
    String day        = jComboBox2.getSelectedItem().toString();
    String tableNum   = jComboBox4.getSelectedItem().toString();
 // client.sendMessage("SHOW " + restaurant + " " + tableNum + " " + day);************
  
    client.sendMessage("SHOW " + restaurant + " "+tableNum+ " " + day);

    new Thread(() -> {
        java.util.List<String> freeTimes = client.readUntilEnd();
        SwingUtilities.invokeLater(() -> {
            if (freeTimes.isEmpty()) {
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"No available times"}));
            } else {
                jComboBox3.setModel(
                    new javax.swing.DefaultComboBoxModel<>(freeTimes.toArray(new String[0]))
                );
            }
        });
    }).start();
                                       
  
        
        /*
        String restaurant = jComboBox1.getSelectedItem().toString();
    String day = jComboBox2.getSelectedItem().toString();
    String tableNum = "1"; // مبدئيًا نفترض دايم الطاولة رقم 1

    try {
        out.println("SHOW " + restaurant + " " + tableNum + " " + day);
        java.util.List<String> freeTimes = new java.util.ArrayList<>();
        String line;

        while ((line = in.readLine()) != null) {
            if (line.equals("END")) break;
            freeTimes.add(line);
        }

        if (freeTimes.isEmpty()) {
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"No available times"}));
        } else {
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(freeTimes.toArray(new String[0])));
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error loading times from server.");
    }
        */
    }//GEN-LAST:event_jButton3ActionPerformed
// button show avilable code ends 
    
  //***********************************************
     
private void timeSelectedActionPerformed(java.awt.event.ActionEvent evt) {
    String restaurant = jComboBox1.getSelectedItem().toString();
    String day = jComboBox2.getSelectedItem().toString();
    String time = jComboBox3.getSelectedItem().toString();
    
    if ("No available times".equals(time)) {
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"No tables"}));
        return;
    }
    
    // Get available tables for this specific time
    client.sendMessage("SHOW_TABLES " + restaurant + " " + day + " " + time);

    new Thread(new Runnable() {
        public void run() {
            final java.util.List<String> availableTables = client.readUntilEnd();
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    if (availableTables.isEmpty()) {
                        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"No tables available"}));
                    } else {
                        String[] tablesArray = availableTables.toArray(new String[availableTables.size()]);
                        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(tablesArray));
                    }
                }
            });
        }
    }).start();
}
    
    //****************************************
    
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    String restaurant = jComboBox1.getSelectedItem().toString();
    String day        = jComboBox2.getSelectedItem().toString();
    String time       = jComboBox3.getSelectedItem().toString();
    String tableNum   = jComboBox4.getSelectedItem().toString(); /////**************************
    if ("No tables available".equals(tableNum) || "No tables".equals(tableNum)) {
    JOptionPane.showMessageDialog(this, "Please choose a valid table.");
    return;
}
    ////************************

       // Include username in the reservation command
    System.out.println("Sending: RESERVE " + username + " " + restaurant + " " + tableNum + " " + day + " " + time);
    if ("No available times".equals(time)) {
        JOptionPane.showMessageDialog(this, "Please choose a valid time.");
        return;
    }

    client.sendMessage("RESERVE "+username+" "+ restaurant +  " " +tableNum + " "+ day + " " + time);

    new Thread(() -> {
        String response = client.readMessage(); 
        SwingUtilities.invokeLater(() -> {
            if (response != null) {
                JOptionPane.showMessageDialog(this, response, "Reservation", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Reservation completed!");
            }
            // Return to MyAccount instead of MainMenu
            Myaccount myAccount = new Myaccount(username);
            myAccount.setVisible(true);
            this.dispose();
        });
    }).start();

/*
String restaurant = jComboBox1.getSelectedItem().toString();
    String day = jComboBox2.getSelectedItem().toString();
    String time = jComboBox3.getSelectedItem().toString();
    String tableNum = "1"; // مؤقت

    if (time.equals("No available times")) {
        JOptionPane.showMessageDialog(this, "Please choose a valid time.");
        return;
    }

    try {
        out.println("RESERVE " + restaurant + " " + tableNum + " " + day + " " + time);
        String response = in.readLine();

        if (response != null) {
            JOptionPane.showMessageDialog(this, response, "Reservation", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Reservation completed!");
        }

        //  نرجع المستخدم للقائمة الرئيسية بعد الحجز
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error while booking reservation.");
    }
*/
    }//GEN-LAST:event_jButton4ActionPerformed
// cofirm buton
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new MakeNewReservation("testUser").setVisible(true));
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
