/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package GUI;
package com.mycompany.lab3;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


/**
 *
 * @author haya9
 */
public class Myaccount extends javax.swing.JFrame {
   
  //$$$$$$$$$$$
    private String currentUsername;  
     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Myaccount.class.getName());

    /**
     * Creates new form Myaccount
     */
    
  
 //$$$$$$$$$$$$$
    public Myaccount(String username) {
        initComponents();
    this.currentUsername=username;
    loadUserReservations();
    applyCustomDesign();
    }
    public Myaccount(){
        initComponents();
    }
 // ===================== ✨ DESIGN ONLY - NO LOGIC CHANGES ✨ =====================
    private void applyCustomDesign() {
        // 1. خلفية النافذة
        getContentPane().setBackground(new Color(245, 240, 230));
        
        // 2. تنسيق العنوان
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 24));
        jLabel1.setForeground(new Color(101, 67, 33));
        
        // 3. تنسيق اللوحة الرئيسية
        jPanel1.setBackground(new Color(245, 240, 230));
        jPanel2.setBackground(new Color(255, 250, 245));
        jPanel2.setBorder(BorderFactory.createLineBorder(new Color(184, 134, 74), 2));
        
        // 4. تنسيق الأزرار
        styleButton(jToggleButton1, "Cancel Reservation");
        styleButton(jToggleButton2, "New Reservation");
        
        // 5. تنسيق النص
        jTextArea1.setBackground(new Color(255, 250, 245));
        jTextArea1.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTextArea1.setForeground(new Color(101, 67, 33));
        
        // 6. تنسيق القائمة
        jList1.setBackground(new Color(255, 250, 245));
        jList1.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jList1.setForeground(new Color(101, 67, 33));
    }

    private void styleButton(JToggleButton btn, String text) {
        btn.setText(text);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btn.setBackground(new Color(184, 134, 74));
        btn.setForeground(Color.WHITE);
        btn.setBorder(BorderFactory.createRaisedBevelBorder());
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        // تأثير Hover
        btn.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                btn.setBackground(new Color(160, 120, 70));
            }
            public void mouseExited(MouseEvent evt) {
                btn.setBackground(new Color(184, 134, 74));
            }
        });
    }
    // ===================== END DESIGN =====================

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("My bookings");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("if you want to cancel any booking click on it then click cancel reservation");
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToggleButton1.setText("cancel reservation");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Make new reservation");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jToggleButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton1))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    // نتأكد فيه اختيار
    String selected = jList1.getSelectedValue();
    if (selected == null || selected.startsWith("No reservations")) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a reservation to cancel.",
                "Cancel",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // مثال النص:
    // Resturant:R1,Day: Sunday,Time: 4-6, Table :1

    try {
        String restaurant = selected.substring(
                selected.indexOf("Resturant:") + "Resturant:".length(),
                selected.indexOf(",Day:")).trim();

        String day = selected.substring(
                selected.indexOf("Day:") + "Day:".length(),
                selected.indexOf(",Time:")).trim();

        String time = selected.substring(
                selected.indexOf("Time:") + "Time:".length(),
                selected.indexOf(", Table")).trim();

        String tableNo = selected.substring(
                selected.indexOf("Table :") + "Table :".length()
        ).trim();

        // نرسل أمر CANCEL للسيرفر
        Client client = new Client();
        client.sendMessage("CANCEL " + currentUsername + " " + restaurant + " " + tableNo + " " + day + " " + time);
        String response = client.readMessage();
        client.close();

        javax.swing.JOptionPane.showMessageDialog(this,
                response,
                "Cancel Reservation",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // نعيد تحميل الحجوزات بعد الحذف
        loadUserReservations();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error while parsing selected reservation.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
MakeNewReservation newRes = new MakeNewReservation(currentUsername);//pass the username
newRes.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Myaccount().setVisible(true));
    }
    //$$$$$$$$$$$$$$$$$
    private void loadUserReservations() {
    // Create a client to talk to server
    Client client = new Client();
    
    // ✅ SEND COMMAND TO GET THIS USER'S RESERVATIONS
    client.sendMessage("GET_MY_RESERVATIONS " + currentUsername);
    
    // Read the response
    java.util.List<String> myReservations = client.readUntilEnd();
    
    // Display in the JList
    if (myReservations.isEmpty() || myReservations.get(0).equals("No reservations found")) {
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "No reservations found" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    } else {
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = myReservations.toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    client.close();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
